version: '2'
services:
    server:
        build: ./docker/server/
        volumes:
            - .:/var/www/html
        ports:
            - 80:80

    mysql:
        image: mysql:5.7.23
        ports:
            - 3306:3306
        volumes:
            - ./init-sql:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: root


