version: '2'
services:
    server:
        image: php:7.2-apache
        volumes:
            - .:/var/www/html
        ports:
            - 80:80

    mysql:
        image: mysql:5.7.23
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root


